### PR TITLE
feat(CSVEntry): allow consumers to pass in custom footer content

### LINKED ISSUE #1690: CSV Entry: Add ability for consumers to add their own buttons below the grid
Product has requested the ability to define custom buttons below the CSV entry table.

Example:

- [ ] Use `ng-content` to allow consumer to pass in rich content
- [ ] Lay out with flexbox row. (use empty span between left and right with the `flex` directive to push contents to each side)
- [ ] Add an `@Input` to control the button layout `footerDirection: 'ltr' | 'rtl' = 'ltr';`
  - This flag should use flex layout to flip the order of footer items.
  - By default our buttons start on the left and consumer buttons on the right

### PR DESCRIPTION
**Pull request by benjamincharity**
also now allows consumer to control footer direction

ISSUES CLOSED: #1690

csv

### CODE REVIEW

**Review by atlwendy — APPROVED** [review]
Would be great to have integration tests...

**Comment by benjamincharity** [comment]
> Would be great to have integration tests...

What could I test? I originally was going to add tests, but it seems I'd really just be testing Angular (`ng-content`) and FlexLayoutModule (`dir`).

**Comment by atlwendy** [comment]
I guess it's more of a visual integration test? For example, when you select `rtl`, the order of the buttons maintains the same, but the whole div moves to the right. 
I didn't mean we need to have it here, more of a wish that we had true integration tests..

**Comment by benjamincharity** [comment]
Ahh yes, totally agree. I was about to even try to test that in mode 'ltr' the divs bounding box was at a different location etc.. but then I remembered I'd be mocking what the browser returned anyway 🙄 

This is _exactly_ why we need visual tests.

**Pull request merged**
